### ISSUE TITLE
Need websocket client support 

### ISSUE THREAD

**Issue by wasabia** [karlseguin/websocket.zig#10]
Is there a plan to support it?

**Comment by karlseguin** [comment]
I never even thought of it. But yes, I think that makes sense. Shouldn't be too hard. Give me a couple days maybe.

**Comment by karlseguin** [comment]
There's a branch now that passes all of the mandatory autobahn tests:
https://github.com/karlseguin/websocket.zig/tree/client

Documentation is https://github.com/karlseguin/websocket.zig/tree/client#client

Would love feedback if you have the opportunity.
