### ISSUE TITLE
Cannot mutate Handler since passed different pointers

### ISSUE THREAD

**Issue by tjk** [karlseguin/websocket.zig#20]
Please let me know if I'm doing something wrong but it seems like `handler` is [copied in server.zig](https://github.com/karlseguin/websocket.zig/blob/master/src/server.zig#L220) and so the mutable `self` pointer is not the same across different hooks... is this expected?

```zig
const Handler = struct {
    conn: *websocket.Conn,
    context: *Context,
    handles: u32,

    pub fn init(_: websocket.Handshake, conn: *websocket.Conn, context: *Context) !Handler {
        return Handler{
            .conn = conn,
            .context = context,
            .handles = 0,
        };
    }

    pub fn handle(self: *Handler, message: websocket.Message) !void {
        self.handles += 1;
    }

    pub fn close(self: *Handler) void {
        std.debug.print("handles: {d}\n", .{self.handles}); // not what i expect
    }
};
```

I know to use `context` for state across handlers but I thought I could put handler-local state within that struct... maybe bad assumption? I'm new to zig so I may be doing something silly. Thanks for the library!

**Comment by karlseguin** [comment]
Ya...`afterInit` and `close` would get a different copy than `handle`. Latest master should make this consistent across all.
