### ISSUE TITLE
src\server.zig:326:28: error: expected type '*os.windows.ws2_32.SOCKET__opaque_4451', found 'c_int'

### ISSUE THREAD

**Issue by albertxavier100** [karlseguin/websocket.zig#23]
Hi team,

I'm new to zig. 

I checkout the branch to `zig-0.11` (commit: `b5370b608000cf264b23faffd376d6495ef6d83a`)
when I run `zig build test`, I got error `src\server.zig:326:28: error: expected type '*os.windows.ws2_32.SOCKET__opaque_4451', found 'c_int'`
My OS is Windows 11, and zig version is `zig-windows-x86_64-0.11.0`.

Please help out!
Any workaround is welcome.

**Comment by karlseguin** [comment]
Hi.

Is this when running the tests? If so, it _might_ be fixed. I can't really test it, but I could reproduce the issue trying to build the tests for windows, and that's working now.  However, I couldn't get it to fail like this when trying to build a non-test executable for windows.
