### ISSUE TITLE
Way to install this package and packed in a lib

### ISSUE THREAD

**Issue by RockChinQ** [karlseguin/websocket.zig#25]
Hi there and thank you for your great work! I'm a greenhand to ziglang and I try to use `websocket.zig` to make another lib. So far I've installed [zigmod](https://github.com/nektro/zigmod) for package management. And I'm using vscode with official Zig language extension. But when I import this lib with the following code:

```zig
const websocket = @import("websocket");
```

I can't not jump to the code of `websocket.zig` in vscode with shortcut `ctrl+Left Click`. I've made sure that `websocket.zig` is in the `.zigmod` dir.

<img width="380" alt="image" src="https://github.com/karlseguin/websocket.zig/assets/45992437/94f3c7ba-6fce-4bd2-9c4b-61e5286d7f75">

I'm not sure this is a issue with `Zig Language Extension` or the `Zigmod Package Manager`. Could you please tell my how to install websocket.zig in the right way, and how to embed it with my lib ? Thank you so much!

**Comment by karlseguin** [comment]
Hi,

The library is available using Zig's built-in package manager.  I've blogged about how to use it, [here](https://www.openmymind.net/learning_zig/coding_in_zig/#build) and here's a [Chinese translation](https://zigcc.github.io/learning-zig/09-coding-in-zig.html#%E7%AC%AC%E4%B8%89%E6%96%B9%E4%BE%9D%E8%B5%96).

I'm not really sure how Zigmod works :(

**Comment by RockChinQ** [comment]
Thank you!
